// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3-bohM5NMom10OMbOBUVPjf1LHZfmff8',
    appId: '1:64422446249:web:1d86f46b48c6dc6a1795b8',
    messagingSenderId: '64422446249',
    projectId: 'chc-mvp',
    authDomain: 'chc-mvp.firebaseapp.com',
    storageBucket: 'chc-mvp.firebasestorage.app',
    measurementId: 'G-ZGP4V8BBRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv98WdKPkwkA5lKJYf-oKvueZcvA5RM6s',
    appId: '1:64422446249:android:f5623f8d1d5604041795b8',
    messagingSenderId: '64422446249',
    projectId: 'chc-mvp',
    storageBucket: 'chc-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSqWERkjkI6MhSXJsMk1YjVE9bJzyYlBM',
    appId: '1:64422446249:ios:b66e0b30392507f31795b8',
    messagingSenderId: '64422446249',
    projectId: 'chc-mvp',
    storageBucket: 'chc-mvp.firebasestorage.app',
    iosClientId: '64422446249-bvetsijii6e070fp3bf1e8sae6i1n2fs.apps.googleusercontent.com',
    iosBundleId: 'fr.florianmousse.chcmvp',
  );
}
